a=int(input("enter the 1st number: "))
b=int(input("enter the 2nd number: "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
