a=int(input("enter the 1st integer number: "))
b=int(input("enter the 2nd integer number: "))
print("Sum of two integer number:")
print(a+b)
c=float(input("enter the 1st float number: "))
d=float(input("enter the 2nd float number: "))
print("Sum of two float number:")
print(c+d)
e=complex(input("enter the 1st complex number: "))
f=complex(input("enter the 2nd complex number: "))
print("Sum of two complex number:")
print(e+f)
